### ISSUE TITLE
EPIC: circle primitives

### ISSUE THREAD

**Issue by eemshi** [bright-wwweb/crbn-ftprnt#1]
- [ ] circle for each category
- [ ] add small a circle inside a category whenever it gets a vote
- [ ] make the circles float
